# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dm-is-schemaless}
  s.version = "0.10.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["brianthecoder"]
  s.date = %q{2009-10-26}
  s.description = %q{A plugin that allows you to easily treat an rdbms like a schemaless store, perfect for something like heroku *wink, wink*}
  s.email = %q{wbsmith83@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "LICENSE",
     "README.rdoc",
     "Rakefile",
     "TODO",
     "VERSION",
     "lib/dm-is-schemaless.rb",
     "lib/dm-is-schemaless.rb",
     "lib/dm-is-schemaless/is/index.rb",
     "lib/dm-is-schemaless/is/index.rb",
     "lib/dm-is-schemaless/is/schemaless.rb",
     "lib/dm-is-schemaless/is/schemaless.rb",
     "lib/dm-is-schemaless/is/version.rb",
     "lib/dm-is-schemaless/is/version.rb",
     "spec/integration/schemaless_spec.rb",
     "spec/models.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "tasks/install.rb",
     "tasks/spec.rb"
  ]
  s.homepage = %q{http://github.com/BrianTheCoder/dm-is-schemales}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{An implementation of friendfeed's schemaless store for rbdms'}
  s.test_files = [
    "spec/integration/schemaless_spec.rb",
     "spec/models.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_runtime_dependency(%q<dm-types>, [">= 0"])
    else
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<dm-types>, [">= 0"])
    end
  else
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<dm-types>, [">= 0"])
  end
end

